# Info:
# http://blog.natefinch.com/2014/07/ci-for-windows-go-packages-with-appveyor.html
# https://discuss.atom.io/t/testing-ci-on-windows-with-appveyor/10690/15
# http://www.appveyor.com/docs/build-configuration
# https://github.com/joefitzgerald/go-plus/blob/master/appveyor.yml

# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# set the clone folder in gopath
clone_folder: c:\gopath\src\github.com\pivotal-golang\cacheddownloader

# environment variables
environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
#  - mkdir %GOPATH%\src\github.com\pivotal-golang\cacheddownloader\
#  - xcopy  %APPVEYOR_BUILD_FOLDER% %GOPATH%\src\github.com\pivotal-golang\cacheddownloader\  /s /e

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set PATH=%PATH%;%GOPATH%\bin
  - cd %APPVEYOR_BUILD_FOLDER%
#  - cd %GOPATH%\src\github.com\pivotal-golang\cacheddownloader
  - ginkgo -r -skipMeasurements -randomizeAllSpecs -race -noColor=true

# to disable automatic tests
test: off

# to disable deployment
deploy: off